name: "Test All JDKs"
on:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        docker-image:
          - clojure:temurin-8-jammy
          - clojure:temurin-11-jammy
          - clojure:temurin-17-jammy
          - clojure:temurin-21-jammy
        clj-version: ["1.10", "1.11", "1.12"]
    container: ${{ matrix.docker-image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore Cache
        uses: actions/cache/restore@v3
        with:
          path: ~/.m2
          key: project-${{ hashFiles('deps.edn') }}

      - name: Run Test
        run: clojure -T:build test :clj '"${{ matrix.clj-version }}"'

      - name: Save Cache
        uses: actions/cache/save@v3
        with:
          path: ~/.m2
          key: project-${{ hashFiles('deps.edn') }}
